[project]
name = "redis-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "graphstate>=1.0.6",
    "groq<1",
    "langchain-groq",
    "langgraph>=1.2.14",
    "langgraph-checkpoint-redis>=0.5.2",
    "redis>=8.1.0",
]

[project.scripts]
redis-agent = "redis_agent:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
